site_name: LinuxProfile
site_url: http://linuxprofile.com
repo_name: linux-profile/linux-profile-plugin
repo_url: https://github.com/linux-profile/linux-profile-plugin

nav:
    - Home: index.md
    - Release Notes: nav/release-notes.md

theme: 
    name: material
    logo: assets/linux-profile-icon.png
    favicon: assets/linux-profile-icon.ico
    features:
        - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/linux-profile
